package frame;

import inner.*;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JButton;

/**
 *
 * @author Maksim
 */
public class MyFrame extends javax.swing.JFrame {

    Operation calculator;

    /**
     * Creates new form MyFrame
     */
    public MyFrame() {

        this.calculator = new Operation();

        initComponents();

        for (Component button : buttonsPanel.getComponents()) {
            JButton currentButton = (JButton) button;
            currentButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    addDigit(e);
                    calculator.setIsOperation(false);
                }
            });
        }

        for (Component button : operationPanel.getComponents()) {
            JButton operationButton = (JButton) button;
            operationButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    setOperation(e);
                    calculator.setIsOperation(true);
                }
            });
        }

        for (Component button : servicePanel.getComponents()) {
            JButton operationButton = (JButton) button;
            operationButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    setServiceOperation(e);

                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        sevenButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        treeButton = new javax.swing.JButton();
        aButton = new javax.swing.JButton();
        nullButton = new javax.swing.JButton();
        commaButton = new javax.swing.JButton();
        digitsPanel = new javax.swing.JPanel();
        digitsField = new javax.swing.JTextField();
        operationPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        subButton = new javax.swing.JButton();
        mulButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        servicePanel = new javax.swing.JPanel();
        deliteAllButton = new javax.swing.JButton();
        deliteLastButton = new javax.swing.JButton();
        equalButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My calc");
        setLocation(new java.awt.Point(100, 100));
        setMaximumSize(new java.awt.Dimension(300, 247));
        setMinimumSize(new java.awt.Dimension(300, 247));
        setResizable(false);
        setSize(new java.awt.Dimension(300, 247));

        jPanel1.setLayout(new java.awt.BorderLayout());

        buttonsPanel.setLayout(new java.awt.GridLayout(4, 3));

        sevenButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sevenButton.setText("7");
        sevenButton.setMinimumSize(new java.awt.Dimension(20, 20));
        sevenButton.setOpaque(false);
        sevenButton.setPreferredSize(new java.awt.Dimension(80, 80));
        buttonsPanel.add(sevenButton);

        eightButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        eightButton.setText("8");
        buttonsPanel.add(eightButton);

        nineButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nineButton.setText("9");
        buttonsPanel.add(nineButton);

        fourButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        fourButton.setText("4");
        buttonsPanel.add(fourButton);

        fiveButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        fiveButton.setText("5");
        buttonsPanel.add(fiveButton);

        sixButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sixButton.setText("6");
        buttonsPanel.add(sixButton);

        oneButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        oneButton.setText("1");
        buttonsPanel.add(oneButton);

        twoButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        twoButton.setText("2");
        buttonsPanel.add(twoButton);

        treeButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        treeButton.setText("3");
        buttonsPanel.add(treeButton);

        aButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        aButton.setEnabled(false);
        aButton.setFocusPainted(false);
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(aButton);

        nullButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nullButton.setText("0");
        buttonsPanel.add(nullButton);

        commaButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        commaButton.setText(".");
        buttonsPanel.add(commaButton);

        jPanel1.add(buttonsPanel, java.awt.BorderLayout.WEST);

        digitsPanel.setLayout(new java.awt.BorderLayout());

        digitsField.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        digitsField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        digitsField.setToolTipText("");
        digitsPanel.add(digitsField, java.awt.BorderLayout.CENTER);

        jPanel1.add(digitsPanel, java.awt.BorderLayout.NORTH);
        digitsPanel.getAccessibleContext().setAccessibleName("");

        operationPanel.setAutoscrolls(true);
        operationPanel.setLayout(new java.awt.GridLayout(4, 1));

        addButton.setBackground(new java.awt.Color(70, 70, 70));
        addButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        addButton.setText("+");
        addButton.setToolTipText("");
        addButton.setPreferredSize(new java.awt.Dimension(80, 80));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        operationPanel.add(addButton);

        subButton.setBackground(new java.awt.Color(70, 70, 70));
        subButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        subButton.setText("-");
        operationPanel.add(subButton);

        mulButton.setBackground(new java.awt.Color(70, 70, 70));
        mulButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        mulButton.setText("*");
        operationPanel.add(mulButton);

        divButton.setBackground(new java.awt.Color(70, 70, 70));
        divButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        divButton.setText("/");
        operationPanel.add(divButton);

        jPanel1.add(operationPanel, java.awt.BorderLayout.CENTER);

        servicePanel.setLayout(new java.awt.GridLayout(4, 1));

        deliteAllButton.setBackground(new java.awt.Color(70, 70, 70));
        deliteAllButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        deliteAllButton.setText("C");
        deliteAllButton.setMaximumSize(new java.awt.Dimension(44, 48));
        deliteAllButton.setMinimumSize(new java.awt.Dimension(44, 48));
        deliteAllButton.setPreferredSize(new java.awt.Dimension(80, 80));
        servicePanel.add(deliteAllButton);

        deliteLastButton.setBackground(new java.awt.Color(70, 70, 70));
        deliteLastButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        deliteLastButton.setText("CE");
        deliteLastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliteLastButtonActionPerformed(evt);
            }
        });
        servicePanel.add(deliteLastButton);

        equalButton.setBackground(new java.awt.Color(70, 70, 70));
        equalButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        equalButton.setText("=");
        servicePanel.add(equalButton);

        bButton.setBackground(new java.awt.Color(70, 70, 70));
        bButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bButton.setText("<html>&plusmn;");
        bButton.setBorderPainted(false);
        servicePanel.add(bButton);

        jPanel1.add(servicePanel, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    private void deliteLastButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addDigit(ActionEvent e) {

        if (calculator.getIsOperation()) {
            digitsField.setText("");
        }

        Pattern pattern = Pattern.compile("^[-]?[[\\d][\\.]]{0,15}$");
        Matcher matcher = pattern.matcher(digitsField.getText());

        if (matcher.find()) {
            String sign = ((JButton) e.getSource()).getText();
            if (!sign.equals(".") || !digitsField.getText().contains(".")) {
                digitsField.setText(digitsField.getText() + sign);
            }
        } else {
            digitsField.getText();
        }
    }

    private void setOperation(ActionEvent e) {
        if (calculator.getOperation() == null) {
            calculator.setA(Float.parseFloat(digitsField.getText()));
            calculator.setOperation(((JButton) e.getSource()).getText());
        } else {
            calculator.setB(Float.parseFloat(digitsField.getText()));
            float result = calculator.action();
            calculator.setA(result);
            calculator.setB(0);
            digitsField.setText(Float.toString(result));
            calculator.setOperation(((JButton) e.getSource()).getText());

        }

    }

    private void setServiceOperation(ActionEvent e) {
        String s = ((JButton) e.getSource()).getText();
        switch (s) {
            case "C":
                digitsField.setText("");
                break;
            case "CE":
                digitsField.setText("");
                calculator.setA(0);
                calculator.setB(0);
                calculator.setOperation(null);
                break;
            case "=":
                calculator.setB(Float.parseFloat(digitsField.getText()));
                digitsField.setText(Float.toString(calculator.action()));
                calculator.setA(0);
                calculator.setB(0);
                calculator.setOperation(null);
                calculator.setIsOperation(true);
                break;
            case "<html>&plusmn;":
                digitsField.setText(Float.toString(Float.parseFloat(digitsField.getText()) * (-1)));
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new MyFrame().setVisible(true);

    }

    // Variables declaration - do not modify
    private javax.swing.JButton aButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton bButton;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton commaButton;
    private javax.swing.JButton deliteAllButton;
    private javax.swing.JButton deliteLastButton;
    private javax.swing.JTextField digitsField;
    private javax.swing.JPanel digitsPanel;
    private javax.swing.JButton divButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mulButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton nullButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JPanel operationPanel;
    private javax.swing.JPanel servicePanel;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton subButton;
    private javax.swing.JButton treeButton;
    private javax.swing.JButton twoButton;
    // End of variables declaration

}
